---
- name: install and configure nginx on ubuntu
  hosts: webservers
  become: true
  tasks:
    - name: install nginx
      package:
        update_cache: true
        name: nginx
        state: latest
    - name: copy nginx file into the server
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
    - name: Enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
    - name: use custom index file
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
