# Purpose - build a playbook to achieve the following things
  # 1. create a user
  # 2. update and upgrade OS
  # 3. install apache and php module
  # 4. change the file and restart apache service
  # 5. add the user and set password
  # 6. use ssh key to allow password less access to the user 
  # 7. add user to sudoers file.

---
- hosts: all
  become: true
  pre_tasks:
    - name: update and upgrade OS (if applicable)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        upgrade: dist
- hosts: webbies
  become: true
  tasks:
    - name: install apache on ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
    - name: customize index.html file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: start and enable service (if required) # not required on Ubuntu
      service:
        name: apache2
        state: started
        enabled: yes
    - name: change the content inside the file
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^Timeout'
        line: Timeout 600
      register: httpstate
    - name: restart apache2 service
      when: httpstate.changed
      service:
        name: apache2
        state: restarted
      register: servicestatus
    - name: print the service restart message
      ansible.builtin.debug:
        var: servicestatus
    - name: create a user twenty (tty) thousand (tsd) euro (eu)
      user:
        name: ttytsdeur
        comment: 28kEu
        shell: /bin/bash
        group: adm
        password: $6$O7Apm80ySZz9Vek9$S0WMjDInZ/jiKH8ekC2EHfWKIU7A0u7OdN9.zHW8Fw03EJe2nmOSxTsWFmrQtIiwCaHzbaU5GyyhR08kYt3Xi/
# password was generated by using following method
# sudo apt install whois
# mkpasswd -m sha-512, password output changes everytime.
    - name: add the user to sudoers file.
      copy:
        src: sudoer_ttytsdeur
        dest: /etc/sudoers.d/ttytsdeur
        group: root
        owner: root
        mode: 0440
    - name: allow passwordless access to the user
      authorized_key:
        user: ttytsdeur
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFNNa5pCq5fRnZ7NIWfUowRCRG6gNUOAEJgfAMHckP67 Ansible my love"