---
- name: print text using msg or variables
  hosts: all
  vars:
    myname: "preetam (BLK)"
  tasks:
    - name: just print hello text
      ansible.builtin.debug:
    - name: just print var
      ansible.builtin.debug:
        var: myname
    - name: print variable and custom message
      ansible.builtin.debug:
        msg: "I {{ myname }} blessed by Lord Krishna (BLK)"
    - name: print the message with verbosity
      ansible.builtin.debug:
        var: myname
        verbosity: 2
# to execute to get verbosity use the following command
# ansible-playbook -i inventory -vv name_of_the_playbook