---
- name: configure webserver with nginx
  hosts: webbies
  become: true
  tasks:
    - name: ensure nginx is installed
      apt:
        update_cache: yes
        name:
          - nginx
        state: latest
    - name: copy nginx config file
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
    - name: enable configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
    - name: copy index file
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
    - name: restart nginx service
      service:
        name: nginx
        state: restarted
        enabled: yes
     